### ISSUE TITLE
Should we be tracking trunk?

### ISSUE THREAD

**Issue by pkevan** [Automattic/vip-docker#20]
If we don't track `trunk` how will updates work?

If we do track `trunk` can we sync during the init, or should it be more frequent?

**Comment by tomjn** [comment]
It's currently hardcoded to 4.7.1, but I'm not fond of tracking trunk, that turns this from a developer environment to a dedicated test environment and that's caused issues for QS 1 users who had to deal with bugs that were known with fixes incoming, such as WP CLI being broken, Jetpack experimental and trunk interacting in strange ways etc
