### ISSUE TITLE
'version' doesn't have any configuration options

### ISSUE THREAD

**Issue by philipjohn** [Automattic/vip-docker#21]
When I run `bin/up` in Ubuntu 16.04, I'm getting the following output:

> Updating containers
> ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

Following that is what looks like the help output for the `docker-compose` command.

I attempted to recreate the containers which produced this:

> $ docker-compose up -d --force-recreate
ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

I also tried `sudo service docker start` and it produced the same error.

`docker ps` reports:

> Cannot connect to the Docker daemon. Is the docker daemon running on this host?

So then I tried to make sure the Docker daemon was running...

> $ dockerd
> FATA[0000] Error starting daemon: pid file found, ensure docker is not running or delete /var/run/docker.pid 
> $ ll /var/run/docker.pid 
> -rw-r--r-- 1 root root 5 Jan 29 11:49 /var/run/docker.pid
> $ sudo rm /var/run/docker.pid 
> $ sudo dockerd &
> INFO[0000] libcontainerd: previous instance of containerd still alive (22154) 
> INFO[0000] [graphdriver] using prior storage driver "aufs" 
> FATA[0001] Error starting daemon: timeout

I also attempted to kill any running instances of docker with `pkill -9 -f docker` and then `sudo service docker start`. Retrying `bin/up` after that produced the same output as the first failed attempt.

**Comment by tomjn** [comment]
I think this is due to the new `docker-compose` v2 format and the version of Docker installed

Follow https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04 to make sure it's pulling from the docker official repo rather than the ubuntu 16 apt repos

**Comment by ethitter** [comment]
We should link to https://docs.docker.com/engine/installation/linux/ubuntu/#/install-using-the-repository in the readme.
